{
    "name":"Farmlink v18",
    "id":"15e11a54-8f8e-4480-aff2-450c3f1d3d9b",
    "ui":[
       {
          "data":{
             "11":{
                "position":{
                   "x":-5.401968002319336,
                   "y":-22.2587947845459,
                   "z":-3.814697265625e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"11"
             },
             "22":{
                "position":{
                   "x":35.95372009277344,
                   "y":3.195864200592041,
                   "z":0
                },
                "size":{
                   "x":4.980000019073486,
                   "y":7.172999858856201,
                   "z":0
                },
                "collapsed":false,
                "appId":"22"
             },
             "12":{
                "position":{
                   "x":13.92171859741211,
                   "y":-13.27560043334961,
                   "z":-1.9073486328125e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"12"
             },
             "23":{
                "position":{
                   "x":35.402008056640625,
                   "y":-4.94601583480835,
                   "z":0
                },
                "size":{
                   "x":5.579999923706055,
                   "y":7.172999858856201,
                   "z":0
                },
                "collapsed":false,
                "appId":"23"
             },
             "14":{
                "position":{
                   "x":9.932549476623535,
                   "y":20.816650390625,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"14"
             },
             "15":{
                "position":{
                   "x":-0.7079141139984131,
                   "y":10.16208553314209,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"15"
             },
             "16":{
                "position":{
                   "x":26.558238983154297,
                   "y":1.6986829042434692,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"16"
             },
             "17":{
                "position":{
                   "x":17.571189880371094,
                   "y":9.354416847229004,
                   "z":-1.9073486328125e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"17"
             },
             "18":{
                "position":{
                   "x":8.133346557617188,
                   "y":5.9214372634887695,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"18"
             },
             "0":{
                "position":{
                   "x":34.307918548583984,
                   "y":-13.234414100646973,
                   "z":9.5367431640625e-07
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"0"
             },
             "3":{
                "position":{
                   "x":24.894054412841797,
                   "y":6.666121006011963,
                   "z":9.5367431640625e-07
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"3"
             },
             "4":{
                "position":{
                   "x":4.799160480499268,
                   "y":-3.447147846221924,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"4"
             },
             "6":{
                "position":{
                   "x":24.181743621826172,
                   "y":-13.264616966247559,
                   "z":1.9073486328125e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"6"
             },
             "7":{
                "position":{
                   "x":-2.3162906169891357,
                   "y":5.11662483215332,
                   "z":9.5367431640625e-07
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"7"
             },
             "8":{
                "position":{
                   "x":-2.365234851837158,
                   "y":-3.642381429672241,
                   "z":3.814697265625e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"8"
             },
             "9":{
                "position":{
                   "x":-2.4061665534973145,
                   "y":-12.231343269348145,
                   "z":3.814697265625e-06
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"9"
             },
             "20":{
                "position":{
                   "x":28.854393005371094,
                   "y":-5.941539764404297,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"20"
             },
             "10":{
                "position":{
                   "x":14.455132484436035,
                   "y":-2.8923001289367676,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"10"
             },
             "21":{
                "position":{
                   "x":43.73810958862305,
                   "y":-10.3506498336792,
                   "z":0
                },
                "size":{
                   "x":7,
                   "y":1.9229999780654907,
                   "z":0
                },
                "collapsed":false,
                "appId":"21"
             }
          },
          "type":"modeleditor",
          "config":{
             "allowCycles":false
          }
       }
    ],
    "version":"1.0.0",
    "device":{
       "build":{
          "project":"cactus",
          "number":"47058927",
          "branch":"master",
          "version":"1.0.0",
          "revision":"c3f2730c982f1aa17ce1942d5c04ace26023e005",
          "timestamp":1622041761000
       },
       "connections":[
          {
             "dest":"0",
             "ports":[
                {
                   "src_port_nr":"0",
                   "dest_port_nr":"0"
                }
             ],
             "src":"6"
          },
          {
             "dest":"4",
             "ports":[
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"0"
                }
             ],
             "src":"7"
          },
          {
             "dest":"12",
             "ports":[
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"0"
                }
             ],
             "src":"9"
          },
          {
             "dest":"16",
             "ports":[
                {
                   "src_port_nr":"6",
                   "dest_port_nr":"6"
                },
                {
                   "src_port_nr":"5",
                   "dest_port_nr":"5"
                },
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"7"
                },
                {
                   "src_port_nr":"4",
                   "dest_port_nr":"4"
                },
                {
                   "src_port_nr":"3",
                   "dest_port_nr":"3"
                },
                {
                   "src_port_nr":"2",
                   "dest_port_nr":"2"
                },
                {
                   "src_port_nr":"1",
                   "dest_port_nr":"1"
                },
                {
                   "src_port_nr":"0",
                   "dest_port_nr":"0"
                }
             ],
             "src":"10"
          },
          {
             "dest":"20",
             "ports":[
                {
                   "src_port_nr":"6",
                   "dest_port_nr":"6"
                }
             ],
             "src":"10"
          },
          {
             "dest":"22",
             "ports":[
                {
                   "src_port_nr":"6",
                   "dest_port_nr":"6"
                }
             ],
             "src":"10"
          },
          {
             "dest":"23",
             "ports":[
                {
                   "src_port_nr":"6",
                   "dest_port_nr":"6"
                }
             ],
             "src":"10"
          },
          {
             "dest":"12",
             "ports":[
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"1"
                }
             ],
             "src":"11"
          },
          {
             "dest":"6",
             "ports":[
                {
                   "src_port_nr":"0",
                   "dest_port_nr":"0"
                }
             ],
             "src":"12"
          },
          {
             "dest":"17",
             "ports":[
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"0"
                }
             ],
             "src":"14"
          },
          {
             "dest":"14",
             "ports":[
                {
                   "src_port_nr":"0",
                   "dest_port_nr":"2"
                }
             ],
             "src":"15"
          },
          {
             "dest":"3",
             "ports":[
                {
                   "src_port_nr":"0",
                   "dest_port_nr":"0"
                }
             ],
             "src":"17"
          },
          {
             "dest":"17",
             "ports":[
                {
                   "src_port_nr":"7",
                   "dest_port_nr":"1"
                }
             ],
             "src":"18"
          }
       ],
       "apps":{
          "11":{
             "name":"INJECT_NODE_RED",
             "type":36464,
             "params":{
                "0":{
                   "name":"INJECTED_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"INJECTED_STRING",
                   "type":"string",
                   "exposition":"inout",
                   "value":""
                }
             }
          },
          "22":{
             "name":"LIGHT",
             "type":4357,
             "params":{
                "0":{
                   "name":"DEBUG_INDEX",
                   "type":"uint8_t",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"DEBUG_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                }
             }
          },
          "12":{
             "name":"AND",
             "type":26234,
             "params":{
                "0":{
                   "name":"GATE_TYPE",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":0
                }
             }
          },
          "23":{
             "name":"TEMPERATURE",
             "type":4357,
             "params":{
                "0":{
                   "name":"DEBUG_INDEX",
                   "type":"uint8_t",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"DEBUG_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                }
             }
          },
          "14":{
             "name":"CONVERT_APP",
             "type":53960,
             "params":{
                "0":{
                   "name":"CONVERT_FROM_INPUT",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":2
                },
                "1":{
                   "name":"CONVERT_TO_BOOL_THRESHOLD",
                   "type":"float",
                   "exposition":"in",
                   "value":1
                }
             }
          },
          "15":{
             "name":"SQUARE_WAVE_APP",
             "type":64506,
             "params":{
                "0":{
                   "name":"SQUARE_CYCLE_MS",
                   "type":"int32_t",
                   "exposition":"in",
                   "value":20
                },
                "1":{
                   "name":"SQUARE_LOW",
                   "type":"int32_t",
                   "exposition":"in",
                   "value":10
                },
                "2":{
                   "name":"SQUARE_HIGH",
                   "type":"int32_t",
                   "exposition":"in",
                   "value":10
                }
             }
          },
          "16":{
             "name":"CO2",
             "type":4357,
             "params":{
                "0":{
                   "name":"DEBUG_INDEX",
                   "type":"uint8_t",
                   "exposition":"inout",
                   "value":6
                },
                "1":{
                   "name":"DEBUG_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                }
             }
          },
          "17":{
             "name":"AND_1",
             "type":26234,
             "params":{
                "0":{
                   "name":"GATE_TYPE",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":0
                }
             }
          },
          "18":{
             "name":"CONSTANT_0",
             "type":36464,
             "params":{
                "0":{
                   "name":"INJECTED_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"INJECTED_STRING",
                   "type":"string",
                   "exposition":"inout",
                   "value":""
                }
             }
          },
          "0":{
             "name":"LED_RED",
             "type":56660,
             "params":{
                "0":{
                   "name":"GPIO_NR",
                   "type":"int32_t",
                   "exposition":"in",
                   "value":32
                },
                "1":{
                   "name":"GPIO_DRV_ID",
                   "type":"uint16_t",
                   "exposition":"in",
                   "value":10932
                },
                "2":{
                   "name":"GPIO_VALUE",
                   "type":"bool",
                   "exposition":"inout",
                   "value":false
                }
             }
          },
          "3":{
             "name":"LED_GREEN",
             "type":56660,
             "params":{
                "0":{
                   "name":"GPIO_NR",
                   "type":"int32_t",
                   "exposition":"in",
                   "value":33
                },
                "1":{
                   "name":"GPIO_DRV_ID",
                   "type":"uint16_t",
                   "exposition":"in",
                   "value":10932
                },
                "2":{
                   "name":"GPIO_VALUE",
                   "type":"bool",
                   "exposition":"inout",
                   "value":false
                }
             }
          },
          "4":{
             "name":"NOT",
             "type":26234,
             "params":{
                "0":{
                   "name":"GATE_TYPE",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":2
                }
             }
          },
          "6":{
             "name":"NOT_2",
             "type":26234,
             "params":{
                "0":{
                   "name":"GATE_TYPE",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":2
                }
             }
          },
          "7":{
             "name":"button1",
             "type":36464,
             "params":{
                "0":{
                   "name":"INJECTED_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"INJECTED_STRING",
                   "type":"string",
                   "exposition":"inout",
                   "value":""
                }
             }
          },
          "8":{
             "name":"button2",
             "type":36464,
             "params":{
                "0":{
                   "name":"INJECTED_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"INJECTED_STRING",
                   "type":"string",
                   "exposition":"inout",
                   "value":""
                }
             }
          },
          "9":{
             "name":"button3",
             "type":36464,
             "params":{
                "0":{
                   "name":"INJECTED_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                },
                "1":{
                   "name":"INJECTED_STRING",
                   "type":"string",
                   "exposition":"inout",
                   "value":""
                }
             }
          },
          "20":{
             "name":"HUMIDITY",
             "type":4357,
             "params":{
                "0":{
                   "name":"DEBUG_INDEX",
                   "type":"uint8_t",
                   "exposition":"inout",
                   "value":6
                },
                "1":{
                   "name":"DEBUG_VALUE",
                   "type":"float",
                   "exposition":"inout",
                   "value":0
                }
             }
          },
          "10":{
             "name":"OPCUA_READ_APP",
             "type":21094,
             "params":{
                "0":{
                   "name":"SERVER",
                   "type":"string",
                   "exposition":"in",
                   "value":"opc.tcp://192.168.178.61:53530/OPCUA/SimulationServer"
                },
                "1":{
                   "name":"USERNAME",
                   "type":"string",
                   "exposition":"in",
                   "value":""
                },
                "2":{
                   "name":"PASSWORD",
                   "type":"string",
                   "exposition":"in",
                   "value":""
                },
                "3":{
                   "name":"SECURITY_MODE",
                   "type":"uint8_t",
                   "exposition":"in",
                   "value":0
                },
                "4":{
                   "name":"SECURITY_POLICY",
                   "type":"string",
                   "exposition":"in",
                   "value":"None"
                },
                "5":{
                   "name":"NODE_NAMESPACE",
                   "type":"uint32_t",
                   "exposition":"in",
                   "value":3
                },
                "6":{
                   "name":"NODE_IDENTIFIER",
                   "type":"uint32_t",
                   "exposition":"in",
                   "value":1002
                },
                "7":{
                   "name":"NODE_IDENTIFIER_STRING",
                   "type":"string",
                   "exposition":"in",
                   "value":""
                }
             }
          },
          "21":{
             "name":"CAN_READ_APP",
             "type":44780,
             "params":{
                "0":{
                   "name":"CAN_DRIVER_ID",
                   "type":"uint16_t",
                   "exposition":"in",
                   "value":0
                },
                "1":{
                   "name":"MESSAGE_ID",
                   "type":"uint32_t",
                   "exposition":"in",
                   "value":0
                }
             }
          }
       }
    }
 }